<?php
/**
 * Admin Class
 * Handles all admin interface functionality
 */

if (!defined('ABSPATH')) {
    exit;
}

class CreditCardManager_Admin {

    public function __construct() {
        $this->init_hooks();
    }

    /**
     * Initialize hooks
     */
    private function init_hooks() {
        add_action('admin_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('add_meta_boxes', array($this, 'add_meta_boxes'));
        add_action('save_post', array($this, 'save_meta_data'));
        add_filter('manage_credit-card_posts_columns', array($this, 'add_admin_columns'));
        add_action('manage_credit-card_posts_custom_column', array($this, 'admin_column_content'), 10, 2);
        add_filter('manage_edit-credit-card_sortable_columns', array($this, 'sortable_columns'));
    }

    /**
     * Initialize component
     */
    public function init() {
        // Component is initialized through hooks
    }

    /**
     * Enqueue admin scripts and styles
     */
    public function enqueue_scripts($hook) {
        global $post_type;

        if ($post_type === 'credit-card' && ($hook === 'post.php' || $hook === 'post-new.php')) {
            wp_enqueue_media();
            wp_enqueue_style(
                'credit-card-admin',
                CCM_PLUGIN_URL . 'assets/admin.css',
                array(),
                CCM_VERSION
            );
            wp_enqueue_script(
                'credit-card-admin',
                CCM_PLUGIN_URL . 'assets/admin.js',
                array('jquery'),
                CCM_VERSION,
                true
            );

            wp_localize_script('credit-card-admin', 'ccm_admin', array(
                'ajax_url' => admin_url('admin-ajax.php'),
                'nonce' => wp_create_nonce('ccm_admin_nonce'),
            ));
        }
    }

    /**
     * Add Meta Boxes
     */
    public function add_meta_boxes() {
        add_meta_box(
            'credit-card-details',
            __('Credit Card Details', 'credit-card-manager'),
            array($this, 'meta_box_callback'),
            'credit-card',
            'normal',
            'high'
        );
    }

    /**
     * Meta Box Callback
     */
    public function meta_box_callback($post) {
        wp_nonce_field('credit_card_meta_box', 'credit_card_meta_box_nonce');

        // Get current values
        $rating = get_post_meta($post->ID, 'rating', true);
        $review_count = get_post_meta($post->ID, 'review_count', true);
        $annual_fee = get_post_meta($post->ID, 'annual_fee', true);
        $joining_fee = get_post_meta($post->ID, 'joining_fee', true);
        $welcome_bonus = get_post_meta($post->ID, 'welcome_bonus', true);
        $welcome_bonus_points = get_post_meta($post->ID, 'welcome_bonus_points', true);
        $welcome_bonus_type = get_post_meta($post->ID, 'welcome_bonus_type', true);
        $cashback_rate = get_post_meta($post->ID, 'cashback_rate', true);
        $reward_type = get_post_meta($post->ID, 'reward_type', true);
        $reward_conversion_rate = get_post_meta($post->ID, 'reward_conversion_rate', true);
        $reward_conversion_value = get_post_meta($post->ID, 'reward_conversion_value', true);
        $credit_limit = get_post_meta($post->ID, 'credit_limit', true);
        $interest_rate = get_post_meta($post->ID, 'interest_rate', true);
        $processing_time = get_post_meta($post->ID, 'processing_time', true);
        $min_income = get_post_meta($post->ID, 'min_income', true);
        $min_age = get_post_meta($post->ID, 'min_age', true);
        $max_age = get_post_meta($post->ID, 'max_age', true);
        $apply_link = get_post_meta($post->ID, 'apply_link', true);
        $featured = get_post_meta($post->ID, 'featured', true);
        $trending = get_post_meta($post->ID, 'trending', true);
        $theme_color = get_post_meta($post->ID, 'theme_color', true);

        // Get array fields
        $pros = get_post_meta($post->ID, 'pros', true) ?: array();
        $cons = get_post_meta($post->ID, 'cons', true) ?: array();
        $best_for = get_post_meta($post->ID, 'best_for', true) ?: array();
        $documents = get_post_meta($post->ID, 'documents', true) ?: array();
        $features = get_post_meta($post->ID, 'features', true) ?: array();

        ?>
        <div class="credit-card-meta-container">

            <!-- JSON Import Section -->
            <div class="ccm-json-import">
                <h3><?php _e('🤖 AI Data Import', 'credit-card-manager'); ?></h3>
                <p><?php _e('Paste JSON data generated by AI to automatically fill all fields. This will save you time when adding new credit cards.', 'credit-card-manager'); ?></p>

                <textarea id="ccm-json-input" class="ccm-json-textarea" placeholder="Paste your JSON data here...">{
  "basic": {
    "rating": 4.5,
    "review_count": 1250,
    "featured": true,
    "trending": false
  },
  "fees": {
    "annual_fee": 2500,
    "joining_fee": 2500,
    "welcome_bonus": "10,000 reward points worth ₹2,500",
    "welcome_bonus_points": 10000,
    "welcome_bonus_type": "points",
    "cashback_rate": "Up to 4% reward rate"
  },
  "rewards": {
    "reward_type": "Points",
    "reward_conversion_rate": "1 Point = 0.25 Rupee",
    "reward_conversion_value": 0.25
  },
  "eligibility": {
    "credit_limit": "Up to ₹10,00,000",
    "interest_rate": "3.49% per month",
    "processing_time": "7-10 working days",
    "min_income": "₹6,00,000 annually",
    "min_age": "21",
    "max_age": "65"
  },
  "lists": {
    "pros": [
      "High reward rate on dining and entertainment",
      "Complimentary airport lounge access",
      "No foreign transaction fees"
    ],
    "cons": [
      "High annual fee",
      "Limited reward categories"
    ],
    "best_for": [
      "Frequent travelers",
      "Dining enthusiasts",
      "Premium lifestyle"
    ],
    "documents": [
      "PAN Card",
      "Aadhaar Card",
      "Salary slips (last 3 months)",
      "Bank statements (last 6 months)"
    ],
    "features": [
      {
        "title": "Lounge Access",
        "description": "Complimentary access to domestic and international airport lounges."
      },
      {
        "title": "Travel Insurance",
        "description": "Comprehensive travel insurance coverage for trips booked with the card."
      }
    ]
  },
  "custom_faqs": [
    {
      "question": "What is the welcome bonus for this card?",
      "answer": "New cardholders can earn 10,000 reward points worth ₹2,500 on meeting the minimum spend requirement."
    },
    {
      "question": "Are there any foreign transaction fees?",
      "answer": "No, this card has zero foreign transaction fees, making it ideal for international travel."
    }
  ]
}</textarea>

                <div class="ccm-json-buttons">
                    <button type="button" id="ccm-import-json" class="ccm-json-btn">
                        <?php _e('📥 Import JSON Data', 'credit-card-manager'); ?>
                    </button>
                    <button type="button" id="ccm-export-json" class="ccm-json-btn secondary">
                        <?php _e('📤 Export Current Data', 'credit-card-manager'); ?>
                    </button>
                    <button type="button" id="ccm-clear-json" class="ccm-json-btn secondary">
                        <?php _e('🗑️ Clear', 'credit-card-manager'); ?>
                    </button>
                </div>

                <div id="ccm-json-status" class="ccm-json-status"></div>

                <details style="margin-top: 15px;">
                    <summary style="cursor: pointer; font-weight: bold;"><?php _e('📖 JSON Format Guide', 'credit-card-manager'); ?></summary>
                    <div style="margin-top: 10px; font-size: 12px; color: #666;">
                        <p><strong>Required sections:</strong></p>
                        <ul>
                            <li><code>basic</code> - Rating, review count, featured/trending flags</li>
                            <li><code>fees</code> - Annual fee, joining fee, welcome bonus details</li>
                            <li><code>rewards</code> - Reward type and conversion rates</li>
                            <li><code>eligibility</code> - Income, age, processing time requirements</li>
                            <li><code>lists</code> - Arrays for pros, cons, best_for, documents</li>
                            <li><code>custom_faqs</code> - Array of question/answer objects</li>
                        </ul>
                        <p><strong>Tips:</strong> All fields are optional. Missing fields will keep existing values.</p>
                    </div>
                </details>
            </div>

            <div class="ccm-field-group">
                <h3><?php _e('Basic Information', 'credit-card-manager'); ?></h3>

                <div class="ccm-field">
                    <label for="rating"><?php _e('Rating (0-5)', 'credit-card-manager'); ?></label>
                    <input type="number" id="rating" name="rating" value="<?php echo esc_attr($rating); ?>" min="0" max="5" step="0.1" />
                </div>

                <div class="ccm-field">
                    <label for="review_count"><?php _e('Review Count', 'credit-card-manager'); ?></label>
                    <input type="number" id="review_count" name="review_count" value="<?php echo esc_attr($review_count); ?>" min="0" />
                </div>

                <div class="ccm-checkbox-group">
                    <input type="checkbox" id="featured" name="featured" value="1" <?php checked($featured, 1); ?> />
                    <label for="featured"><?php _e('Featured Card', 'credit-card-manager'); ?></label>
                </div>

                <div class="ccm-checkbox-group">
                    <input type="checkbox" id="trending" name="trending" value="1" <?php checked($trending, 1); ?> />
                    <label for="trending"><?php _e('Trending Card', 'credit-card-manager'); ?></label>
                </div>

                <div class="ccm-field">
                    <label for="theme_color"><?php _e('Theme Color', 'credit-card-manager'); ?></label>
                    <input type="color" id="theme_color" name="theme_color" value="<?php echo esc_attr($theme_color ?: '#1e40af'); ?>" />
                </div>
            </div>

            <div class="ccm-field-group">
                <h3><?php _e('Fees & Benefits', 'credit-card-manager'); ?></h3>

                <div class="ccm-field">
                    <label for="annual_fee"><?php _e('Annual Fee', 'credit-card-manager'); ?></label>
                    <input type="number" id="annual_fee" name="annual_fee" value="<?php echo esc_attr($annual_fee); ?>" placeholder="2500" />
                </div>

                <div class="ccm-field">
                    <label for="joining_fee"><?php _e('Joining Fee', 'credit-card-manager'); ?></label>
                    <input type="number" id="joining_fee" name="joining_fee" value="<?php echo esc_attr($joining_fee); ?>" placeholder="2500" />
                </div>

                <div class="ccm-field">
                    <label for="welcome_bonus"><?php _e('Welcome Bonus Description', 'credit-card-manager'); ?></label>
                    <input type="text" id="welcome_bonus" name="welcome_bonus" value="<?php echo esc_attr($welcome_bonus); ?>" placeholder="10,000 reward points worth ₹2,500" />
                </div>

                <div class="ccm-field">
                    <label for="welcome_bonus_points"><?php _e('Welcome Bonus Points/Amount', 'credit-card-manager'); ?></label>
                    <input type="number" id="welcome_bonus_points" name="welcome_bonus_points" value="<?php echo esc_attr($welcome_bonus_points); ?>" min="0" />
                </div>

                <div class="ccm-field">
                    <label for="welcome_bonus_type"><?php _e('Welcome Bonus Type', 'credit-card-manager'); ?></label>
                    <select id="welcome_bonus_type" name="welcome_bonus_type">
                        <option value="points" <?php selected($welcome_bonus_type, 'points'); ?>><?php _e('Points', 'credit-card-manager'); ?></option>
                        <option value="money" <?php selected($welcome_bonus_type, 'money'); ?>><?php _e('Money', 'credit-card-manager'); ?></option>
                        <option value="cashback" <?php selected($welcome_bonus_type, 'cashback'); ?>><?php _e('Cashback', 'credit-card-manager'); ?></option>
                    </select>
                </div>

                <div class="ccm-field">
                    <label for="cashback_rate"><?php _e('Cashback/Reward Rate', 'credit-card-manager'); ?></label>
                    <input type="text" id="cashback_rate" name="cashback_rate" value="<?php echo esc_attr($cashback_rate); ?>" placeholder="Up to 4% reward rate" />
                </div>

                <div class="ccm-field">
                    <label for="reward_type"><?php _e('Primary Reward Type', 'credit-card-manager'); ?></label>
                    <input type="text" id="reward_type" name="reward_type" value="<?php echo esc_attr($reward_type); ?>" placeholder="e.g., Points, Cashback, NeuCoins, Scapia Coins" />
                    <small style="color: #666; font-size: 12px; display: block; margin-top: 5px;">
                        <?php _e('Enter the type of rewards this card offers (Points, Cashback, NeuCoins, Scapia Coins, etc.)', 'credit-card-manager'); ?>
                    </small>
                </div>

                <div class="ccm-field">
                    <label for="reward_conversion_rate"><?php _e('Reward Conversion Rate', 'credit-card-manager'); ?></label>
                    <input type="text" id="reward_conversion_rate" name="reward_conversion_rate" value="<?php echo esc_attr($reward_conversion_rate); ?>" placeholder="e.g., 1 NeuCoin = 1 Rupee" />
                    <small style="color: #666; font-size: 12px; display: block; margin-top: 5px;">
                        <?php _e('Describe how the rewards convert to real value (e.g., "1 NeuCoin = 1 Rupee", "100 Points = 25 Rupees")', 'credit-card-manager'); ?>
                    </small>
                </div>

                <div class="ccm-field">
                    <label for="reward_conversion_value"><?php _e('Conversion Value (for calculations)', 'credit-card-manager'); ?></label>
                    <input type="number" id="reward_conversion_value" name="reward_conversion_value" value="<?php echo esc_attr($reward_conversion_value); ?>" step="0.01" min="0" placeholder="1.00" />
                    <small style="color: #666; font-size: 12px; display: block; margin-top: 5px;">
                        <?php _e('Numerical value for calculations. E.g., if 1 NeuCoin = 1 Rupee, enter 1.00. If 100 Points = 25 Rupees, enter 0.25', 'credit-card-manager'); ?>
                    </small>
                </div>
            </div>

            <div class="ccm-field-group">
                <h3><?php _e('Eligibility & Terms', 'credit-card-manager'); ?></h3>

                <div class="ccm-field">
                    <label for="credit_limit"><?php _e('Credit Limit', 'credit-card-manager'); ?></label>
                    <input type="text" id="credit_limit" name="credit_limit" value="<?php echo esc_attr($credit_limit); ?>" placeholder="Up to ₹10,00,000" />
                </div>

                <div class="ccm-field">
                    <label for="interest_rate"><?php _e('Interest Rate', 'credit-card-manager'); ?></label>
                    <input type="text" id="interest_rate" name="interest_rate" value="<?php echo esc_attr($interest_rate); ?>" placeholder="3.49% per month" />
                </div>

                <div class="ccm-field">
                    <label for="processing_time"><?php _e('Processing Time', 'credit-card-manager'); ?></label>
                    <input type="text" id="processing_time" name="processing_time" value="<?php echo esc_attr($processing_time); ?>" placeholder="7-10 working days" />
                </div>

                <div class="ccm-field">
                    <label for="min_income"><?php _e('Minimum Income', 'credit-card-manager'); ?></label>
                    <input type="text" id="min_income" name="min_income" value="<?php echo esc_attr($min_income); ?>" placeholder="₹6,00,000 annually" />
                </div>

                <div class="ccm-field">
                    <label for="min_age"><?php _e('Minimum Age', 'credit-card-manager'); ?></label>
                    <input type="text" id="min_age" name="min_age" value="<?php echo esc_attr($min_age); ?>" placeholder="21 years" />
                </div>

                <div class="ccm-field">
                    <label for="max_age"><?php _e('Maximum Age', 'credit-card-manager'); ?></label>
                    <input type="text" id="max_age" name="max_age" value="<?php echo esc_attr($max_age); ?>" placeholder="65 years" />
                </div>

                <div class="ccm-field">
                    <label for="apply_link"><?php _e('Application Link', 'credit-card-manager'); ?></label>
                    <input type="url" id="apply_link" name="apply_link" value="<?php echo esc_url($apply_link); ?>" placeholder="https://www.bank.com/apply" />
                </div>
            </div>

            <div class="ccm-field-group">
                <h3><?php _e('Pros', 'credit-card-manager'); ?></h3>
                    <div class="ccm-array-field" id="pros-field">
                   <?php if (!empty($pros)): ?>
                       <?php foreach ($pros as $index => $pro): ?>
                           <div class="ccm-array-item">
                               <input type="text" name="pros[]" value="<?php echo esc_attr($pro); ?>" placeholder="Enter a pro" />
                               <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                           </div>
                       <?php endforeach; ?>
                   <?php else: ?>
                       <div class="ccm-array-item">
                           <input type="text" name="pros[]" value="" placeholder="Enter a pro" />
                           <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                       </div>
                   <?php endif; ?>
                   <button type="button" class="ccm-add-item" onclick="addArrayItem('pros-field', 'pros[]', 'Enter a pro')"><?php _e('Add Pro', 'credit-card-manager'); ?></button>
               </div>
           </div>

           <div class="ccm-field-group">
               <h3><?php _e('Cons', 'credit-card-manager'); ?></h3>
               <div class="ccm-array-field" id="cons-field">
                   <?php if (!empty($cons)): ?>
                       <?php foreach ($cons as $index => $con): ?>
                           <div class="ccm-array-item">
                               <input type="text" name="cons[]" value="<?php echo esc_attr($con); ?>" placeholder="Enter a con" />
                               <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                           </div>
                       <?php endforeach; ?>
                   <?php else: ?>
                       <div class="ccm-array-item">
                           <input type="text" name="cons[]" value="" placeholder="Enter a con" />
                           <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                       </div>
                   <?php endif; ?>
                   <button type="button" class="ccm-add-item" onclick="addArrayItem('cons-field', 'cons[]', 'Enter a con')"><?php _e('Add Con', 'credit-card-manager'); ?></button>
               </div>
           </div>

           <div class="ccm-field-group">
               <h3><?php _e('Best For', 'credit-card-manager'); ?></h3>
               <div class="ccm-array-field" id="best-for-field">
                   <?php if (!empty($best_for)): ?>
                       <?php foreach ($best_for as $index => $item): ?>
                           <div class="ccm-array-item">
                               <input type="text" name="best_for[]" value="<?php echo esc_attr($item); ?>" placeholder="Enter target audience" />
                               <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                           </div>
                       <?php endforeach; ?>
                   <?php else: ?>
                       <div class="ccm-array-item">
                           <input type="text" name="best_for[]" value="" placeholder="Enter target audience" />
                           <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                       </div>
                   <?php endif; ?>
                   <button type="button" class="ccm-add-item" onclick="addArrayItem('best-for-field', 'best_for[]', 'Enter target audience')"><?php _e('Add Item', 'credit-card-manager'); ?></button>
               </div>
           </div>

           <div class="ccm-field-group">
               <h3><?php _e('Required Documents', 'credit-card-manager'); ?></h3>
               <div class="ccm-array-field" id="documents-field">
                   <?php if (!empty($documents)): ?>
                       <?php foreach ($documents as $index => $document): ?>
                           <div class="ccm-array-item">
                               <input type="text" name="documents[]" value="<?php echo esc_attr($document); ?>" placeholder="Enter required document" />
                               <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                           </div>
                       <?php endforeach; ?>
                   <?php else: ?>
                       <div class="ccm-array-item">
                           <input type="text" name="documents[]" value="" placeholder="Enter required document" />
                           <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                       </div>
                   <?php endif; ?>
                   <button type="button" class="ccm-add-item" onclick="addArrayItem('documents-field', 'documents[]', 'Enter required document')"><?php _e('Add Document', 'credit-card-manager'); ?></button>
               </div>
           </div>

           <div class="ccm-field-group">
                <h3><?php _e('Key Features', 'credit-card-manager'); ?></h3>
                <div class="ccm-array-field" id="features-field">
                    <?php if (!empty($features)): ?>
                        <?php foreach ($features as $index => $feature): ?>
                            <div class="ccm-feature-item-editor">
                                <input type="text" name="features[<?php echo $index; ?>][title]" value="<?php echo esc_attr($feature['title']); ?>" placeholder="Feature Title" />
                                <textarea name="features[<?php echo $index; ?>][description]" placeholder="Feature Description"><?php echo esc_textarea($feature['description']); ?></textarea>
                                <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this.parentElement)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="ccm-feature-item-editor">
                            <input type="text" name="features[0][title]" value="" placeholder="Feature Title" />
                            <textarea name="features[0][description]" placeholder="Feature Description"></textarea>
                            <button type="button" class="ccm-remove-item" onclick="removeArrayItem(this.parentElement)"><?php _e('Remove', 'credit-card-manager'); ?></button>
                        </div>
                    <?php endif; ?>
                    <button type="button" class="ccm-add-item" onclick="addFeatureItem()"><?php _e('Add Feature', 'credit-card-manager'); ?></button>
                </div>
            </div>

       <div class="ccm-field-group">
           <h3><?php _e('Frequently Asked Questions (FAQs)', 'credit-card-manager'); ?></h3>
           <div class="ccm-array-field" id="custom-faqs-field">
               <?php
               $custom_faqs = get_post_meta($post->ID, 'custom_faqs', true) ?: array();
               if (!empty($custom_faqs)): ?>
                   <?php foreach ($custom_faqs as $index => $faq): ?>
                       <div class="ccm-faq-item">
                           <div class="ccm-field">
                               <label><?php _e('Question', 'credit-card-manager'); ?></label>
                               <input type="text" name="custom_faqs[<?php echo $index; ?>][question]" value="<?php echo esc_attr($faq['question']); ?>" placeholder="Enter FAQ question" />
                           </div>
                           <div class="ccm-field">
                               <label><?php _e('Answer', 'credit-card-manager'); ?></label>
                               <textarea name="custom_faqs[<?php echo $index; ?>][answer]" rows="3" placeholder="Enter FAQ answer"><?php echo esc_textarea($faq['answer']); ?></textarea>
                           </div>
                           <button type="button" class="ccm-remove-item" onclick="removeFaqItem(this)"><?php _e('Remove FAQ', 'credit-card-manager'); ?></button>
                       </div>
                   <?php endforeach; ?>
               <?php else: ?>
                   <div class="ccm-faq-item">
                       <div class="ccm-field">
                           <label><?php _e('Question', 'credit-card-manager'); ?></label>
                           <input type="text" name="custom_faqs[0][question]" value="" placeholder="Enter FAQ question" />
                       </div>
                       <div class="ccm-field">
                           <label><?php _e('Answer', 'credit-card-manager'); ?></label>
                           <textarea name="custom_faqs[0][answer]" rows="3" placeholder="Enter FAQ answer"></textarea>
                       </div>
                       <button type="button" class="ccm-remove-item" onclick="removeFaqItem(this)"><?php _e('Remove FAQ', 'credit-card-manager'); ?></button>
                   </div>
               <?php endif; ?>
               <button type="button" class="ccm-add-item" onclick="addFaqItem()"><?php _e('Add FAQ', 'credit-card-manager'); ?></button>
           </div>
           <p style="color: #666; font-size: 12px; margin-top: 10px;">
               <?php _e('Add custom FAQs specific to this credit card. These will be displayed along with automatically generated FAQs based on card data.', 'credit-card-manager'); ?>
           </p>
       </div>
       </div>

       <?php
   }

   /**
    * Save Meta Data
    */
   public function save_meta_data($post_id) {
       // Verify nonce
       if (!isset($_POST['credit_card_meta_box_nonce']) ||
           !wp_verify_nonce($_POST['credit_card_meta_box_nonce'], 'credit_card_meta_box')) {
           return;
       }

       // Check if user has permission
       if (!current_user_can('edit_post', $post_id)) {
           return;
       }

       // Don't save on autosave
       if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
           return;
       }

       // Only save for credit-card post type
       if (get_post_type($post_id) !== 'credit-card') {
           return;
       }

       // Save simple fields
       $simple_fields = array(
           'rating', 'review_count',
           'welcome_bonus', 'welcome_bonus_points', 'welcome_bonus_type', 'cashback_rate',
           'reward_type', 'reward_conversion_rate', 'reward_conversion_value',
           'credit_limit', 'interest_rate', 'processing_time', 'min_income',
           'min_age', 'max_age', 'apply_link', 'theme_color'
       );

       foreach ($simple_fields as $field) {
           if (isset($_POST[$field])) {
               update_post_meta($post_id, $field, sanitize_text_field($_POST[$field]));
           }
       }

       // Save numeric fields
       $numeric_fields = array('annual_fee', 'joining_fee');
       foreach ($numeric_fields as $field) {
           if (isset($_POST[$field])) {
               update_post_meta($post_id, $field, absint($_POST[$field]));
           }
       }

       // Save boolean fields
       update_post_meta($post_id, 'featured', isset($_POST['featured']) ? 1 : 0);
       update_post_meta($post_id, 'trending', isset($_POST['trending']) ? 1 : 0);

       // Save array fields
       $array_fields = array('pros', 'cons', 'best_for', 'documents');
       foreach ($array_fields as $field) {
           if (isset($_POST[$field]) && is_array($_POST[$field])) {
               $clean_array = array_filter(array_map('sanitize_text_field', $_POST[$field]));
               update_post_meta($post_id, $field, $clean_array);
           }
       }

       // Save features
        if (isset($_POST['features']) && is_array($_POST['features'])) {
            $clean_features = array();
            foreach ($_POST['features'] as $feature) {
                if (!empty($feature['title'])) {
                    $clean_features[] = array(
                        'title' => sanitize_text_field($feature['title']),
                        'description' => sanitize_textarea_field($feature['description']),
                    );
                }
            }
            update_post_meta($post_id, $field, $clean_features);
        }

       // Save custom FAQs
       if (isset($_POST['custom_faqs']) && is_array($_POST['custom_faqs'])) {
           $clean_faqs = array();
           foreach ($_POST['custom_faqs'] as $faq) {
               if (!empty($faq['question']) || !empty($faq['answer'])) {
                   $clean_faqs[] = array(
                       'question' => sanitize_text_field($faq['question']),
                       'answer' => sanitize_textarea_field($faq['answer'])
                   );
               }
           }
           update_post_meta($post_id, 'custom_faqs', $clean_faqs);
       } else {
           delete_post_meta($post_id, 'custom_faqs');
       }
   }

   /**
    * Add Admin Columns
    */
   public function add_admin_columns($columns) {
       $new_columns = array();
       foreach ($columns as $key => $value) {
           $new_columns[$key] = $value;
           if ($key === 'title') {
               $new_columns['card_image'] = __('Image', 'credit-card-manager');
               $new_columns['rating'] = __('Rating', 'credit-card-manager');
               $new_columns['annual_fee'] = __('Annual Fee', 'credit-card-manager');
               $new_columns['network_type'] = __('Network', 'credit-card-manager');
               $new_columns['bank'] = __('Bank', 'credit-card-manager');
               $new_columns['featured'] = __('Featured', 'credit-card-manager');
           }
       }
       return $new_columns;
   }

   /**
    * Admin Column Content
    */
   public function admin_column_content($column, $post_id) {
       switch ($column) {
           case 'card_image':
               if (has_post_thumbnail($post_id)) {
                   echo get_the_post_thumbnail($post_id, array(50, 50));
               } else {
                   echo '-';
               }
               break;

           case 'rating':
               $rating = get_post_meta($post_id, 'rating', true);
               if ($rating) {
                   echo esc_html($rating) . '/5 ⭐';
               } else {
                   echo '-';
               }
               break;

           case 'annual_fee':
               $fee = get_post_meta($post_id, 'annual_fee', true);
               echo $fee ? esc_html($fee) : '-';
               break;

           case 'network_type':
               $terms = get_the_terms($post_id, 'network-type');
               if ($terms && !is_wp_error($terms)) {
                   $names = wp_list_pluck($terms, 'name');
                   echo esc_html(implode(', ', $names));
               } else {
                   echo '-';
               }
               break;

           case 'bank':
               $terms = get_the_terms($post_id, 'store');
               if ($terms && !is_wp_error($terms)) {
                   $names = wp_list_pluck($terms, 'name');
                   echo esc_html(implode(', ', $names));
               } else {
                   echo '-';
               }
               break;

           case 'featured':
               $featured = get_post_meta($post_id, 'featured', true);
               echo $featured ? '✅' : '-';
               break;
       }
   }

   /**
    * Sortable Columns
    */
   public function sortable_columns($columns) {
       $columns['rating'] = 'rating';
       $columns['annual_fee'] = 'annual_fee';
       return $columns;
   }
}
